Update the input data format for genome SVs
broadinstitute/seqr-loading-pipelines pull request #381
Opened 2022-12-22 16:44 UTC by ShifaSZ

See ticket https://github.com/broadinstitute/seqr/issues/3064

2023-01-03 15:41 UTC, hanars requested changes
The idea behind having a separate PR for the tests and then branching off of it for this PR was to make it really clear which data is changing because of function change. You do not achieve that here. You add a whole bunch of new rows here in the new format, and then test them. You need to add those rows to the test fixtures in the test change PR and update the tests accordingly, so in this PR I'm not seeing changed to, say, the GQ of samples when there are no code changes related to GQ

2023-01-05 16:05 UTC, ShifaSZ commented
Okay. I will use the same data rows with updated prediction fields.

2023-01-05 20:26 UTC, hanars requested changes
Overall looks good, just one small request to add a test for the new fields

2023-01-05 20:26 UTC, hanars commented on sv_pipeline/genome/load_data_tests.py
> +        gnomad_svs_ID=None, gnomad_svs_AF=None, gnomad_svs_AC=None, gnomad_svs_AN=None, pos=789481,
I'd prefer to test one row where we can test that the new fields are populated

2023-01-06 16:17 UTC, hanars approved these changes
Approved, but we should first merge the test branch and then merge this branch to master, don't merge this into the test branch

2023-01-09 15:52 UTC, ShifaSZ commented
The gnomAD ID format was changed. I think you may want to look it over again.

2023-01-09 16:06 UTC, hanars approved these changes

2023-01-09 16:08 UTC, merged